---
# tasks file for ansible-role-win-member-dns
#- name: DNS Client
#  win_dns_client:
#    adapter_names: "{{ dns_client_adapter }}"
#    ipv4_addresses: ["{{ dns_client_dns_server_ip }}"]

- name: Configure DNS
  ansible.windows.win_powershell:
    script: files/configure-dns.ps1 --dns_client_adapter "{{ dns_client_adapter }} --dns_client_dns_server_ip "{{ dns_client_dns_server_ip }}"
