---
# tasks file for ansible-r-win-member-dns

- name: DNS Client
  win_dns_client:
    adapter_names: "{{ dns_client_adapter }}"
    ipv4_addresses: "{{ dns_client_dns_server_ip }}"
  when: dns_client_configure